config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, except: %i[new create]

  resources :search, only: [:index]

  get '/my_spaces', to: 'pages#my_spaces'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
  validates :start_date, :end_date, presence: true
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :title, :space_type, :price, :location, presence: true

  validates :space_type, inclusion: { in: ['Car sticker', 'Tattoo', 'Backpack', 'Legal name change', 'Front lawn'],
    message: "%{value} is not a valid space type" }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_title_and_space_type, against: [ :title, :space_type ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user)
  end

  def new
    @booking = Booking.new

    @space = Space.find(params[:space_id])
  end

  def create
    @space = Space.find(params[:space_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.space = @space
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.confirmed = params[:booking][:confirmed]
    if @booking.save
      redirect_to my_spaces_path
    else
      render :my_spaces_path
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path(@user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @user = current_user
    @bookings = Booking.where("user_id = ?", params[:user_id])
  end

  def my_spaces
    @spaces = Space.where(user: current_user)
    @bookings = Booking.all

    space_ids = []
    @spaces.each do |space|
      space_ids << space.id
    end

    @my_bookings = @bookings.select do |booking|
      space_ids.include?(booking.space_id)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController


end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  def index
    if params[:query].present?
      @spaces = Space.search_by_title_and_space_type(params[:query])
      @all_spaces = false
    else
      @spaces = Space.all
      @all_spaces = true
    end

    @markers = @spaces.geocoded.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
        info_window: render_to_string(partial: "info_window", locals: { space: space }),
        image_url: helpers.asset_url("potato.jpg")
      }
    end
  end

  def show
    @space = Space.find(params[:id])
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy
    redirect_to my_spaces_path
  end

  private

  # def set_space
  #   @space = Space.find(params[:id])
  # end

  def space_params
    params.require(:space).permit(:title, :space_type, :location, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container mt-5">
  <h1><%= current_user.first_name %>'s Bookings:</h1>
  <div class="row pb-5 mt-3">
  <% @bookings.each do |booking| %>
    <div class="col-12 col-md-6">
      <div class="card-product">
        <% if booking.space.photo.attached? %>
          <%= cl_image_tag booking.space.photo.key%>
        <% else %>
          <%= image_tag "potato.jpg"%>
        <% end %>
        <div class="card-product-infos col-sm-6">
          <% if booking.confirmed == true %>
            <h6 style="color:green; font-weight: bold;">Accepted</h6>
          <% elsif booking.confirmed == false %>
            <h6 style="color:red; font-weight: bold;">Rejected</h6>
          <% else %>
            <h6 style="color:orange; font-weight:bold;">Awaiting confirmation</h6>
          <% end %>
          <p>Space: <%= booking.space.title %></p>
          <p>Type: <%= booking.space.space_type %></p>
          <%# <p>From: <%= booking.start_date %>
          <%# <p>To: <%= booking.end_date %>
          <% if booking.space.space_type == 'Tattoo' %>
            <p>Duration: FOREVER</p>
            <p>Total price: £<%= booking.space.price %></p>
          <% else %>
            <p>Duration: <%= (booking.end_date - booking.start_date).to_i %> days</p>
            <p>Price: £<%= booking.space.price %>/day</p>
            <p>Total price: £<%= booking.space.price * (booking.end_date - booking.start_date).to_i %></p>
          <% end %>
        </div>
          <div class="justify-content-right col-sm">
            <%= link_to 'Edit booking', bookings_path, class: 'btn btn-secondary btn-sm btn-block' %>
            <%= link_to 'Cancel booking', booking_path(booking), method: :delete, class: 'btn btn-outline-dark btn-sm btn-block', data: {confirm: "Are you sure?"} %>
          </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new booking</h3>
        <%= simple_form_for [@space, @booking] do |f| %>
          <%= f.input :start_date, placeholder: 'start date', as: :date, html5: true %>
          <%= f.input :end_date, placeholder: 'end date', as: :date, html5: true %>
          <%= f.submit class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h2><%= @booking.space.title %></h2>
<p>Type of ad-space: <%= @booking.space.space_type %></p>
<p>Price: £<%= @booking.space.price %></p>
<p>Owner: <%= @booking.space.user.first_name %> <%= @booking.space.user.last_name %></p>
<p>From: <%= @booking.start_date %></p>
<p>To: <%= @booking.end_date %></p>

<%= link_to "All spaces", spaces_path, class: 'btn btn-secondary' %>
<%= link_to "Back to bookings page", bookings_path, class: 'btn btn-outline-dark' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiteSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <% unless action_name == "home" %>
        <div class="navbar-container"><%= render "shared/navbar" %></div>
      <% end %>
      <div class="content-container"><%= yield %></div>
      <% unless action_name == "home" %>
        <div class="footer-container"><%= render "shared/footer" %></div>
      <% end %>
      <%= render 'shared/flashes' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= image_path "banner.jpg" %>);">
  <div class="container">
    <div><%= image_tag "logo_KO.png", class: "landing-logo"  %></div>
    <div style= "height: 250px"><h1><span data-controller="typed-js" ></span></h1></div>
    <div><%= link_to "Find your space", spaces_path, class: "btn btn-ghost" %></div>
  </div>

</div>


<%#= link_to 'My listed spaces', my_spaces_path %>
<%#= link_to 'Spaces to let', spaces_path %>
<%#= link_to 'My bookings', bookings_path(@user) %>

<%#= need this last one to link to the user's bookings, not the owner's %>
<%#= link_to "Sign in", new_user_session_path %>
<%#= link_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/pages/my_spaces.html.erb
<div class="home-container mt-5">

  <%= link_to "Create new space", new_space_path, class: 'btn btn-dark border mb-3' %>
  <div class="row">
    <div class="col-6">
      <h1><%= current_user.first_name %>'s Spaces To Let</h1>
      <% @spaces.each do |space| %>
        <div class="card-product position-relative">
          <% if space.photo.attached? %>
            <%= cl_image_tag space.photo.key%>
          <% else %>
            <%= image_tag "potato.jpg", class: "img" %>
          <% end %>
          <div class="card-product-infos">
            <div class="">
              <h2><%= link_to space.title, space_path(space) %></h2>
              <p><%= space.space_type %></p>
              <% if space.space_type == 'Tattoo' %>
              <p>£<%= space.price %>/FOREVER</p>
              <% else %>
              <p>£<%= space.price %>/day</p>
              <% end %>
            </div>
            <div class="">
              <%= link_to "Delete this space", space_path(space), method: :delete, class: 'btn btn-secondary btn-sm', style: "color:white", data: {confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>
      <% end %><br><br>
    </div>
    <div class="col-6">
      <h1>Pending Bookings</h1>
        <% @my_bookings.each do |booking| %>
          <% if booking.confirmed.nil? %>
            <div class="card-product pending">
              <% if booking.space.photo.attached? %>
                <%= cl_image_tag booking.space.photo.key, class: "img"%>
              <% else %>
                <%= image_tag "potato.jpg", class: "img" %>
              <% end %>
              <div class="card-product-infos">
                <h2><strong><%= booking.space.title %></strong></h2>
                <p>Booked by: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
                <% if booking.space.space_type == 'Tattoo' %>
                <p><%= booking.start_date %></p>
                <p>Total price: £<%= booking.space.price %></p>
                <% else %>
                <p><%= booking.start_date %> for <%= (booking.end_date - booking.start_date).to_i %> days</p>
                <p>Total price: £<%= booking.space.price * (booking.end_date - booking.start_date).to_i %></p>
                <% end %>
                <div class="row my-1">
                  <div class="col">
                    <%= simple_form_for (booking) do |f| %>
                      <%= f.hidden_field :confirmed, value: true %>
                      <%= f.submit 'Accept', class: 'btn btn-secondary btn-sm' %>
                    <% end %>
                  </div>
                  <div class="col">
                    <%= simple_form_for (booking) do |f| %>
                      <%= f.hidden_field :confirmed, value: false %>
                      <%= f.submit 'Reject', class: 'btn btn-outline-dark btn-sm' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <b></b>
        <hr>
      <h1>Approved Bookings</h1>
        <% @my_bookings.each do |booking| %>
            <% if booking.confirmed == true %>
              <div class="card-product approved">
                <% if booking.space.photo.attached? %>
                  <%= cl_image_tag booking.space.photo.key, class: "img"%>
                <% else %>
                  <%= image_tag "potato.jpg", class: "img" %>
                <% end %>
                <div class="card-product-infos">
                <h2><strong><%= booking.space.title %></strong></h2>
                <p>Booked by: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
                <% if booking.space.space_type == 'Tattoo' %>
                <p><%= booking.start_date %></p>
                <p>Total price: £<%= booking.space.price %></p>
                <% else %>
                <p><%= booking.start_date %> for <%= (booking.end_date - booking.start_date).to_i %> days</p>
                <p>Total price: £<%= booking.space.price * (booking.end_date - booking.start_date).to_i %></p>
                <% end %>
              </div>
            <% end %>
        <% end %>
        <b></b>
        <hr>
      <h1>Rejected Bookings</h1>
      <% @my_bookings.each do |booking| %>
          <% if booking.confirmed == false %>
            <div class="card-product rejected">
              <% if booking.space.photo.attached? %>
                <%= cl_image_tag booking.space.photo.key, class: "img"%>
              <% else %>
                <%= image_tag "potato.jpg", class: "img" %>
              <% end %>
              <div class="card-product-infos">
                <h2><strong><%= booking.space.title %></strong></h2>
                <p>Booked by: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
                <% if booking.space.space_type == 'Tattoo' %>
                <p><%= booking.start_date %></p>
                <p>Total price: £<%= booking.space.price %></p>
                <% else %>
                <p><%= booking.start_date %> for <%= (booking.end_date - booking.start_date).to_i %> days</p>
                <p>Total price: £<%= booking.space.price * (booking.end_date - booking.start_date).to_i %></p>
                <% end %>
            </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-dark alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times" style="color:white;"></i>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-dark alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times" style="color:white;"></i>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Ramtheman/white-space"><i class="fab fa-github"></i></a>
    <%# <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a> %>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Team PhaseBook
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo">
      <img src="app/assets/images/logo.png" alt="">
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%# <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      <%# </li>  %>
      <li class="nav-item">
        <%= link_to "My Spaces", my_spaces_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Spaces", spaces_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bookings", bookings_path(@user), class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "obi.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if current_user  %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %>
        <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/spaces/_info_window.html.erb
<h2><%= space.title %></h2>
<p><%= space.location %></p>

app/views/spaces/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel"><%= space.title %></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container mt-5">
          <div class="card-product">
            <% if space.photo.attached? %>
              <%= cl_image_tag space.photo.key, style:"height:250px"%>
            <% else %>
              <%= image_tag "potato.jpg", style:"height:250px" %>
            <% end %>
              <div class="card-product-infos">
                <h2><%= space.title %></h2>
                <p>Type of ad-space: <%= space.space_type %></p>
                <p>Price: £<%= space.price %></p>
                <p>Owner: <%= space.user.first_name %> <%= space.user.last_name %></p>
              </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to 'Book', new_space_booking_path(space), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/edit.html.erb
<h1>who gonna edit this edit page</h1>

app/views/spaces/index.html.erb
<div class="container mt-5">
  <% if @all_spaces == true %>
    <h2>Newly added spaces</h2>
    <div class="row pb-5 mt-3">
      <% @spaces[0...2].each do |space| %>
        <div class="col-12 col-md-6">
          <div class="card-product grow">
            <% if space.photo.attached? %>
              <%= cl_image_tag space.photo.key, class: "image"%>
            <% else %>
              <%= image_tag "potato.jpg", class: "img" %>
            <% end %>
            <div class="card-product-infos">
              <h4><%= link_to space.title, space_path(space) %></h4>
              <p>Owner: <%= space.user.first_name %> <%= space.user.last_name %></p>
              <p>-------------------------</p>
              <p><%= space.space_type %></p>
              <% if space.space_type == "Tattoo" %>
                <p>£<%= space.price %>/FOREVER</p>
              <% else %>
                <p>£<%= space.price %>/day</p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="container mt-5" style="padding: 0px;">
    <h2>Search spaces</h2>
    <div id="SearchForm" >
      <div class="col-6" style="padding: 0px;">
        <%= form_tag spaces_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a space" %>
        <% end %>
      </div>
        <%= submit_tag "Search", class: "btn btn-dark" %>
        <% if @all_spaces == false %>
          <%= button_to "Back to All Spaces", spaces_path(params[query: '']), class: 'btn btn-outline-dark' %>
        <% end %>
    </div>
  </div>

  <br>
  <h1><%= @all_spaces ? "All spaces" : "Search results" %></h1>


  <div class="row pb-5 mt-3">
    <% @spaces.each do |space| %>
      <div class="col-12 col-md-6">
        <%# <%= link_to space_path(space), class: "list-link" do %>
        <%# <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Launch demo modal</button> %>
          <div class="card-product grow" id="example" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <% if space.photo.attached? %>
                <%= cl_image_tag space.photo.key, class: "img"%>
            <% else %>
              <%= image_tag "potato.jpg", class: "img" %>
            <% end %>
            <div class="card-product-infos">
              <h2><%= link_to space.title, space_path(space) %></h2>
              <p>Owner: <%= space.user.first_name %> <%= space.user.last_name %></p>
              <p>-------------------------</p>
              <p><%= space.space_type %></p>
              <% if space.space_type == "Tattoo" %>
                <p>£<%= space.price %>/FOREVER</p>
              <% else %>
                <p>£<%= space.price %>/day</p>
              <% end %>
            </div>
            <%# Modal: %>

          </div>

      </div>
    <% end %>
  </div>

  <h3> Where you can find our spaces </h3>
  <div class="row pb-5 mt-3">
    <div style="width: 100%; height: 600px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new space</h3>
        <%= simple_form_for(@space) do |f| %>
          <%= f.input :title, placeholder: 'Name your ad-space' %>
          <% space_types = ['Car sticker', 'Tattoo', 'Backpack', 'Legal name change', 'Front lawn'] %>
          <%= f.input :space_type, as: :select, collection: space_types, prompt:'Type of space', label: false %>

          <%= f.input :price, placeholder: 'Price per day' %>
          <%= f.input :location,
                      placeholder: 'Where is the ad-space?',
                      input_html: {
                        data: { geocoder_target: "location" },
                        id: 'result',
                        class: 'd-none'
                      },
                      wrapper_html: { data: { controller: "geocoder",
                      geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
          <%= f.input :photo, as: :file %>

          <%= f.submit class: 'btn btn-dark' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="container mt-5">
  <div class="col-12 col-md-6">
      <h1>Ad-space in question:</h1>
        <div class="card-product grow">

          <% if @space.photo.attached? %>
            <%= cl_image_tag @space.photo.key, style:"height:250px"%>
          <% else %>
            <%= image_tag "potato.jpg", style:"height:250px" %>
          <% end %>
            <div class="card-product-infos">
              <h2><%= @space.title %></h2>
              <p>Type of ad-space: <%= @space.space_type %></p>
              <p>Price: £<%= @space.price %></p>
              <p>Owner: <%= @space.user.first_name %> <%= @space.user.last_name %></p>
            </div>

        </div>

    <% if @space.user != current_user %>
      <%= link_to 'Book this space', new_space_booking_path(@space), class: 'btn btn-outline-dark' %>
    <% end %>
    <%= link_to 'Back to spaces list', spaces_path, class: 'btn btn-outline-secondary' %>

  </div>

</div>